name: agenciave_dash
description: "Dashboards interativa para a Agência Vê"
version: 0.0.1
homepage: https://dash.mangatrix.net

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  asyncstate: ^2.1.1-dev.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_getit: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.3.2
  signals_flutter: ^5.5.0
  syncfusion_flutter_charts: ^27.1.50
  table_calendar: ^3.1.2
  top_snackbar_flutter: ^3.1.0
  validatorless: ^1.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
